### ISSUE TITLE
Error when call     await FlutterCallkitIncoming.endAllCalls();

### ISSUE THREAD

**Issue by Davud44** [hiennguyen92/flutter_callkit_incoming#12]
PlatformException (PlatformException(error, call.arguments() must not be null, , null))

**Comment by hiennguyen92** [comment]
Hi @Davud44 
I am not able to reproduce this issue.

**Comment by marcoberetta96** [comment]
@hiennguyen92 here some more details.
Happens anytime when calling `endAllCalls()`.
Testing on Android.
Hope this helps.

```
I/flutter (21398): PlatformException(error, call.arguments() must not be null, , null)
I/flutter (21398): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter (21398): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter (21398): <asynchronous suspension>
I/flutter (21398): #2      FlutterCallkitIncoming.endAllCalls (package:flutter_callkit_incoming/flutter_callkit_incoming.dart:58:5)
I/flutter (21398): <asynchronous suspension>
```

**Comment by mtmfuture** [comment]
yes i do have same issue on ios but i think this happen of RTC engin becuse when i do comment some code of RTC API it works fine

**Comment by hiennguyen92** [comment]
Ok, I'll double check it.

**Comment by hiennguyen92** [comment]
Hi @TouseefAQ,

I just deployed version 1.0.1.
please update it

**Comment by marcoberetta96** [comment]
Hi @hiennguyen92 @Davud44 
Just tested version 1.0.1 on iOS and Android. Now `FlutterCallkitIncoming.endAllCalls()` works!
I think this issue can be closed :)
