### ISSUE TITLE
[Bug] not working on Android 12

### ISSUE THREAD

**Issue by marcoberetta96** [hiennguyen92/flutter_callkit_incoming#20]
This is happening when calling `FlutterCallkitIncoming.showCallkitIncoming(params)` with the example's params.
It happens only on Android 12.

```
I/flutter ( 8366): PlatformException(error, com....: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
I/flutter ( 8366): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., , null)
I/flutter ( 8366): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter ( 8366): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter ( 8366): <asynchronous suspension>
I/flutter ( 8366): #2      FlutterCallkitIncoming.showCallkitIncoming (package:flutter_callkit_incoming/flutter_callkit_incoming.dart:39:5)
I/flutter ( 8366): <asynchronous suspension>
```

**Comment by marcoberetta96** [comment]
@hiennguyen92 I made a PR for this
https://github.com/hiennguyen92/flutter_callkit_incoming/pull/24
