### ISSUE TITLE
`java.lang.ExceptionInInitializerError` when starting a WebRTC call on Android

### ISSUE THREAD

**Issue by ipainchaud** [hiennguyen92/flutter_callkit_incoming#339]
Hi Guys!

We have started an app with a simple use of `flutter_callkit_incoming`. We have only the ability of execute outgoing calls at the moment. Our implementation works great on iOS and performs all the intended effects beautifully. When debugging on Android using the "Android Studio"'s launch, it works as intended as well. The issue appears when we install the apk either from Google Play or from `adb`. Then the application crashes as soon as we start a call. Everything goes well during and after the call to `FlutterCallkitIncoming.startCall(...)`, but very shortly after that call we get the following:

```
07-25 14:56:37.763 31195 31195 D AndroidRuntime: Shutting down VM
07-25 14:56:37.764 31195 31195 E AndroidRuntime: FATAL EXCEPTION: main
07-25 14:56:37.764 31195 31195 E AndroidRuntime: Process: com.cie.appname, PID: 31195
07-25 14:56:37.764 31195 31195 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at o0.y.<init>(ObjectMapper.java:16)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at com.hiennv.flutter_callkit_incoming.Utils$Companion.getGsonInstance(Utils.kt:3)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at com.hiennv.flutter_callkit_incoming.SharedPreferencesUtilsKt.addCall(SharedPreferencesUtils.kt:2)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at com.hiennv.flutter_callkit_incoming.CallkitIncomingBroadcastReceiver.onReceive(CallkitIncomingBroadcastReceiver.kt:15)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: o0.w.values []
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum.enumValues(Enum.java:272)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum$1.create(Enum.java:279)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum$1.create(Enum.java:277)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum.getSharedConstants(Enum.java:291)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Class.getEnumConstantsShared(Class.java:2461)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Class.getEnumConstants(Class.java:2447)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at q0.h.c(MapperConfig.java:1)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at q0.i.<clinit>(MapperConfigBase.java:1)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	... 14 more
07-25 14:56:37.764 31195 31195 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: o0.w.values []
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2103)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	at java.lang.Enum.enumValues(Enum.java:269)
07-25 14:56:37.764 31195 31195 E AndroidRuntime: 	... 23 more
```

This error is observed using `./adb logcat`.

Our app is using flutter_webrtc to make video calls and the error is observed on android 13

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (5 available)
[✓] Network resources
```

Anybody else has the same issue?

**Comment by hiennguyen92** [comment]
I'm not sure about this issue. however, I observed the logcat you sent. can you try to update this file like this one? 
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/dev/android/consumer-rules.pro
