### ISSUE TITLE
java.lang.SecurityException: com.myapplication: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by Jai05-techie** [hiennguyen92/flutter_callkit_incoming#468]
Hi Team,

Recently, we have been encountering issues with Android 14 devices and reported on Firebase crashlytics.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapplication/com.hiennv.flutter_callkit_incoming.CallkitIncomingActivity}: java.lang.SecurityException: com.myapplication: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by hiennguyen92** [comment]
please using 2.0.0+2

**Comment by mjjoshi** [comment]
Not working
