### ISSUE TITLE
Regression on Android alert no-custom/custom in 1.0.5-1.0.6 (works on 1.0.3)

### ISSUE THREAD

**Issue by kmoreau** [hiennguyen92/flutter_callkit_incoming#87]
Hello,

I update the lib on 1.0.6 and i saw that there was a regression on the Android part : 

On NO-full screen notifications of incoming call (alert no-custom/custom) when I press 'accept' the app doesn't launch on my android anymore ... BUT it's work nice on FULL SCREEN alert. 
On iOS side, all work nice :) 

Also the custom UI is different (no more app name and layout issues)
It would come from your modification here:

`if (Build.MANUFACTURER.equals("Xiaomi", ignoreCase = true)) {
                //Ignore
            } else {
                notificationBuilder.setStyle(NotificationCompat.DecoratedCustomViewStyle())
            }`

I tested on the lib version : 
1.0.3 : OK
1.0.5 : KO
1.0.6 : KO

I have a Xiaomi Redmi Note 5 on Android 9 (MIUI Global 11.0.3).

thanks for the lib & and regular updates.

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+7 please try again.

**Comment by zionnite** [comment]
Yes @hiennguyen92, accept button on version 1.0.1+7 will relaunch the app. I noticed it when my app was in the background.

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

**Comment by kmoreau** [comment]
Hello,

i try v1.0.1+8 version and it's ko again on Android :/ 

When android device receive call (device unlock and home displayed), the notification call appears and i click on Accept button and nothing append if app in not in backgroud.
Same test if app is in background and my app crashed.
If my app is in foreground, when the call notification ring my app instantly crash too ...

=> it works even less than the v1.0.1+7 because app don't relaunch :/

It's the stacktrace when foreground app crash when call received (in silent mode)

`D/AndroidRuntime(15937): Shutting down VM
E/AndroidRuntime(15937): FATAL EXCEPTION: main
E/AndroidRuntime(15937): Process: x.y.android.dev, PID: 15937
E/AndroidRuntime(15937): java.lang.RuntimeException: Unable to start service com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService@450233d with Intent { cmp=x.y.android.dev/com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService (has extras) }: java.lang.IllegalArgumentException: at least one timing must be non-zero (timings=[0])
E/AndroidRuntime(15937): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3722)
E/AndroidRuntime(15937): 	at android.app.ActivityThread.access$1700(ActivityThread.java:200)
E/AndroidRuntime(15937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
E/AndroidRuntime(15937): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15937): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(15937): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(15937): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15937): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(15937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(15937): Caused by: java.lang.IllegalArgumentException: at least one timing must be non-zero (timings=[0])
E/AndroidRuntime(15937): 	at android.os.VibrationEffect$Waveform.validate(VibrationEffect.java:533)
E/AndroidRuntime(15937): 	at android.os.VibrationEffect.createWaveform(VibrationEffect.java:201)
E/AndroidRuntime(15937): 	at android.os.VibrationEffect.createWaveform(VibrationEffect.java:174)
E/AndroidRuntime(15937): 	at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.playVibrator(CallkitSoundPlayerService.kt:57)
E/AndroidRuntime(15937): 	at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.onStartCommand(CallkitSoundPlayerService.kt:29)
E/AndroidRuntime(15937): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3700)
E/AndroidRuntime(15937): 	... 8 more
I/Process (15937): Sending signal. PID: 15937 SIG: 9`


EDIT :

if i put my android in non-silent mode (ring on). App won't crash BUT no ring alert displayed ... i receive directly 'missed call' notification.


Do you need more info to identify the problem ?
Thanks for your work :)

**Comment by hiennguyen92** [comment]
ok, let me check

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2

**Comment by kmoreau** [comment]
Hello,

So in 1.0.2, when the app is in foreground it's ok, the app won't relaunch and accept behavior works ! :)

But i have again the same problem when the app is in background/killed ... the app won't launch if i click on accept button.

new case : It's seem the lock call full screen appears 1 sec and pass directly in missing call ... i don't have the time to click on accept button :/

**Comment by hiennguyen92** [comment]
I checked but can't reproduce it.  you can try with version 1.0.2+1
